# Generated by Django 5.1.3 on 2024-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_rename_juegos_juego_rename_mercancias_mercancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mercancia', verbose_name='imagen'),
        ),
    ]
