# Generated by Django 5.1.3 on 2024-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_mercancia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='tipomercancias',
            field=models.ManyToManyField(to='foro.tipomercancia', verbose_name='Tipo de Mercancia'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='tipomercancias',
            field=models.ManyToManyField(to='foro.tipomercancia', verbose_name='Tipo de Mercancia'),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='juegosito',
            field=models.ManyToManyField(to='foro.juego', verbose_name='juegos asociados'),
        ),
    ]
